# will parse the branch name for the substring before an integer (i.e TEAM-22-Review-CI-workflow-for-optimizations)
# and if it exists, prepend the body with a link to that ticket in jira (if the repo using this action has autolinked references enabled)
name: Update Pull Request with Linked Ticket Comment
    
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        BRANCH: ${{ github.head_ref }}
        BODY: ${{ github.event.pull_request.body }}
      with:
          script: |
            const ticket = (process.env.BRANCH).split(/\D+$/g)[0]
            if (ticket) github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ticket + "\n" + (process.env.BODY)
            })
